// =================================================
/// Method name constants for the social.near contract.
pub const SOCIAL_NEAR_METHODS_CONST: SOCIAL_NEAR_METHODS_CONST_TYPE = SOCIAL_NEAR_METHODS_CONST_TYPE {
    storage_deposit: "storage_deposit",
    storage_withdraw: "storage_withdraw",
    storage_unregister: "storage_unregister",
    storage_balance_bounds: "storage_balance_bounds",
    storage_balance_of: "storage_balance_of",
    get_accounts: "get_accounts",
    get_account: "get_account",
    get_account_count: "get_account_count",
    get: "get",
    keys: "keys",
    set: "set",
    get_node_count: "get_node_count",
    get_nodes: "get_nodes",
    get_node: "get_node",
    grant_write_permission: "grant_write_permission",
    debug_get_permissions: "debug_get_permissions",
    is_write_permission_granted: "is_write_permission_granted",
    migrate_state: "migrate_state",
    genesis_init_node_count: "genesis_init_node_count",
    genesis_init_nodes: "genesis_init_nodes",
    genesis_init_accounts: "genesis_init_accounts",
    get_version: "get_version",
    get_shared_storage_pool: "get_shared_storage_pool",
    shared_storage_pool_deposit: "shared_storage_pool_deposit",
    share_storage: "share_storage",
    get_account_storage: "get_account_storage",
    new: "new",
    set_status: "set_status",
    get_status: "get_status",
};
// =================================================
/// String constants for social.near contract method names.
pub struct SOCIAL_NEAR_METHODS_CONST_TYPE {
    pub storage_deposit: &'static str,
    pub storage_withdraw: &'static str,
    pub storage_unregister: &'static str,
    pub storage_balance_bounds: &'static str,
    pub storage_balance_of: &'static str,
    pub get_accounts: &'static str,
    pub get_account: &'static str,
    pub get_account_count: &'static str,
    pub get: &'static str,
    pub keys: &'static str,
    pub set: &'static str,
    pub get_node_count: &'static str,
    pub get_nodes: &'static str,
    pub get_node: &'static str,
    pub grant_write_permission: &'static str,
    pub debug_get_permissions: &'static str,
    pub is_write_permission_granted: &'static str,
    pub migrate_state: &'static str,
    pub genesis_init_node_count: &'static str,
    pub genesis_init_nodes: &'static str,
    pub genesis_init_accounts: &'static str,
    pub get_version: &'static str,
    pub get_shared_storage_pool: &'static str,
    pub shared_storage_pool_deposit: &'static str,
    pub share_storage: &'static str,
    pub get_account_storage: &'static str,
    pub new: &'static str,
    pub set_status: &'static str,
    pub get_status: &'static str,
}
// =================================================
// =================================================
// copyright 2026 by sleet.near