// =================================================
/// Method name constants for the DCL v2 contract.
///
/// All 113 methods as reported by `near contract inspect` on
/// `dclv2.ref-labs.near` (mainnet) and `dclv2.ref-dev.testnet` (testnet).
pub const DCLV2_METHODS_CONST: DCLV2_METHODS_CONST_TYPE = DCLV2_METHODS_CONST_TYPE {
    accept_next_owner: "accept_next_owner",
    add_liquidity: "add_liquidity",
    append_liquidity: "append_liquidity",
    batch_add_liquidity: "batch_add_liquidity",
    batch_burn_v_liquidity: "batch_burn_v_liquidity",
    batch_mint_v_liquidity: "batch_mint_v_liquidity",
    batch_remove_liquidity: "batch_remove_liquidity",
    batch_update_liquidity: "batch_update_liquidity",
    burn_v_liquidity: "burn_v_liquidity",
    callback_post_withdraw_asset: "callback_post_withdraw_asset",
    callback_post_withdraw_near: "callback_post_withdraw_near",
    cancel_next_owner: "cancel_next_owner",
    cancel_order: "cancel_order",
    claim_charged_fee: "claim_charged_fee",
    clear_pool_whitelist: "clear_pool_whitelist",
    confirm_next_owner: "confirm_next_owner",
    create_pool: "create_pool",
    exchange_callback_post_ft_transfer_call_withdraw: "exchange_callback_post_ft_transfer_call_withdraw",
    extend_frozenlist_tokens: "extend_frozenlist_tokens",
    extend_operators: "extend_operators",
    find_order: "find_order",
    ft_on_transfer: "ft_on_transfer",
    get_client_echo_sender_whitelist: "get_client_echo_sender_whitelist",
    get_client_echo_token_whitelist: "get_client_echo_token_whitelist",
    get_contract_storage_report: "get_contract_storage_report",
    get_frozenlist_tokens: "get_frozenlist_tokens",
    get_liquidity: "get_liquidity",
    get_liquidity_range: "get_liquidity_range",
    get_liquidity_view: "get_liquidity_view",
    get_market_depth_list: "get_market_depth_list",
    get_marketdepth: "get_marketdepth",
    get_metadata: "get_metadata",
    get_order: "get_order",
    get_pointorder_range: "get_pointorder_range",
    get_pool: "get_pool",
    get_pool_whitelist: "get_pool_whitelist",
    get_pools: "get_pools",
    get_referral_whitelist: "get_referral_whitelist",
    get_secure_sender_whitelist: "get_secure_sender_whitelist",
    get_user_asset: "get_user_asset",
    get_user_mft_asset: "get_user_mft_asset",
    get_user_storage_detail: "get_user_storage_detail",
    get_vip_user_discount: "get_vip_user_discount",
    grant_next_owner: "grant_next_owner",
    is_pool_account_allowed: "is_pool_account_allowed",
    is_valid_referral: "is_valid_referral",
    list_active_orders: "list_active_orders",
    list_history_orders: "list_history_orders",
    list_liquidities: "list_liquidities",
    list_liquidity_views: "list_liquidity_views",
    list_mft_supply: "list_mft_supply",
    list_pools: "list_pools",
    list_user_assets: "list_user_assets",
    list_user_mft_assets: "list_user_mft_assets",
    list_vip_users: "list_vip_users",
    merge_liquidity: "merge_liquidity",
    mft_balance_of: "mft_balance_of",
    mft_metadata: "mft_metadata",
    mft_resolve_transfer: "mft_resolve_transfer",
    mft_total_supply: "mft_total_supply",
    mft_transfer: "mft_transfer",
    mft_transfer_all_call: "mft_transfer_all_call",
    mft_transfer_call: "mft_transfer_call",
    migrate: "migrate",
    migrate_old_client_echo_whitelist: "migrate_old_client_echo_whitelist",
    mint_v_liquidity: "mint_v_liquidity",
    modify_protocol_fee_rate: "modify_protocol_fee_rate",
    modify_storage_params: "modify_storage_params",
    new: "new",
    nft_approve: "nft_approve",
    nft_is_approved: "nft_is_approved",
    nft_metadata: "nft_metadata",
    nft_resolve_transfer: "nft_resolve_transfer",
    nft_revoke: "nft_revoke",
    nft_revoke_all: "nft_revoke_all",
    nft_supply_for_owner: "nft_supply_for_owner",
    nft_token: "nft_token",
    nft_tokens: "nft_tokens",
    nft_tokens_for_owner: "nft_tokens_for_owner",
    nft_total_supply: "nft_total_supply",
    nft_transfer: "nft_transfer",
    nft_transfer_call: "nft_transfer_call",
    pause_contract: "pause_contract",
    pause_pool: "pause_pool",
    predict_add_liquidity: "predict_add_liquidity",
    predict_hotzap: "predict_hotzap",
    predict_remove_liquidity: "predict_remove_liquidity",
    quote: "quote",
    quote_by_output: "quote_by_output",
    remove_client_echo_sender_whitelist: "remove_client_echo_sender_whitelist",
    remove_client_echo_token_whitelist: "remove_client_echo_token_whitelist",
    remove_frozenlist_tokens: "remove_frozenlist_tokens",
    remove_liquidity: "remove_liquidity",
    remove_operators: "remove_operators",
    remove_referral_whitelist: "remove_referral_whitelist",
    remove_secure_sender_whitelist: "remove_secure_sender_whitelist",
    remove_vip_user: "remove_vip_user",
    resume_contract: "resume_contract",
    resume_pool: "resume_pool",
    set_farming_contract_id: "set_farming_contract_id",
    set_pool_whitelist: "set_pool_whitelist",
    set_vip_user: "set_vip_user",
    storage_balance_bounds: "storage_balance_bounds",
    storage_balance_of: "storage_balance_of",
    storage_deposit: "storage_deposit",
    storage_unregister: "storage_unregister",
    storage_withdraw: "storage_withdraw",
    upgrade: "upgrade",
    upsert_client_echo_sender_whitelist: "upsert_client_echo_sender_whitelist",
    upsert_client_echo_token_whitelist: "upsert_client_echo_token_whitelist",
    upsert_referral_whitelist: "upsert_referral_whitelist",
    upsert_secure_sender_whitelist: "upsert_secure_sender_whitelist",
    withdraw_asset: "withdraw_asset",
};
// =================================================
/// String constants for DCL v2 contract method names.
pub struct DCLV2_METHODS_CONST_TYPE {
    pub accept_next_owner: &'static str,
    pub add_liquidity: &'static str,
    pub append_liquidity: &'static str,
    pub batch_add_liquidity: &'static str,
    pub batch_burn_v_liquidity: &'static str,
    pub batch_mint_v_liquidity: &'static str,
    pub batch_remove_liquidity: &'static str,
    pub batch_update_liquidity: &'static str,
    pub burn_v_liquidity: &'static str,
    pub callback_post_withdraw_asset: &'static str,
    pub callback_post_withdraw_near: &'static str,
    pub cancel_next_owner: &'static str,
    pub cancel_order: &'static str,
    pub claim_charged_fee: &'static str,
    pub clear_pool_whitelist: &'static str,
    pub confirm_next_owner: &'static str,
    pub create_pool: &'static str,
    pub exchange_callback_post_ft_transfer_call_withdraw: &'static str,
    pub extend_frozenlist_tokens: &'static str,
    pub extend_operators: &'static str,
    pub find_order: &'static str,
    pub ft_on_transfer: &'static str,
    pub get_client_echo_sender_whitelist: &'static str,
    pub get_client_echo_token_whitelist: &'static str,
    pub get_contract_storage_report: &'static str,
    pub get_frozenlist_tokens: &'static str,
    pub get_liquidity: &'static str,
    pub get_liquidity_range: &'static str,
    pub get_liquidity_view: &'static str,
    pub get_market_depth_list: &'static str,
    pub get_marketdepth: &'static str,
    pub get_metadata: &'static str,
    pub get_order: &'static str,
    pub get_pointorder_range: &'static str,
    pub get_pool: &'static str,
    pub get_pool_whitelist: &'static str,
    pub get_pools: &'static str,
    pub get_referral_whitelist: &'static str,
    pub get_secure_sender_whitelist: &'static str,
    pub get_user_asset: &'static str,
    pub get_user_mft_asset: &'static str,
    pub get_user_storage_detail: &'static str,
    pub get_vip_user_discount: &'static str,
    pub grant_next_owner: &'static str,
    pub is_pool_account_allowed: &'static str,
    pub is_valid_referral: &'static str,
    pub list_active_orders: &'static str,
    pub list_history_orders: &'static str,
    pub list_liquidities: &'static str,
    pub list_liquidity_views: &'static str,
    pub list_mft_supply: &'static str,
    pub list_pools: &'static str,
    pub list_user_assets: &'static str,
    pub list_user_mft_assets: &'static str,
    pub list_vip_users: &'static str,
    pub merge_liquidity: &'static str,
    pub mft_balance_of: &'static str,
    pub mft_metadata: &'static str,
    pub mft_resolve_transfer: &'static str,
    pub mft_total_supply: &'static str,
    pub mft_transfer: &'static str,
    pub mft_transfer_all_call: &'static str,
    pub mft_transfer_call: &'static str,
    pub migrate: &'static str,
    pub migrate_old_client_echo_whitelist: &'static str,
    pub mint_v_liquidity: &'static str,
    pub modify_protocol_fee_rate: &'static str,
    pub modify_storage_params: &'static str,
    pub new: &'static str,
    pub nft_approve: &'static str,
    pub nft_is_approved: &'static str,
    pub nft_metadata: &'static str,
    pub nft_resolve_transfer: &'static str,
    pub nft_revoke: &'static str,
    pub nft_revoke_all: &'static str,
    pub nft_supply_for_owner: &'static str,
    pub nft_token: &'static str,
    pub nft_tokens: &'static str,
    pub nft_tokens_for_owner: &'static str,
    pub nft_total_supply: &'static str,
    pub nft_transfer: &'static str,
    pub nft_transfer_call: &'static str,
    pub pause_contract: &'static str,
    pub pause_pool: &'static str,
    pub predict_add_liquidity: &'static str,
    pub predict_hotzap: &'static str,
    pub predict_remove_liquidity: &'static str,
    pub quote: &'static str,
    pub quote_by_output: &'static str,
    pub remove_client_echo_sender_whitelist: &'static str,
    pub remove_client_echo_token_whitelist: &'static str,
    pub remove_frozenlist_tokens: &'static str,
    pub remove_liquidity: &'static str,
    pub remove_operators: &'static str,
    pub remove_referral_whitelist: &'static str,
    pub remove_secure_sender_whitelist: &'static str,
    pub remove_vip_user: &'static str,
    pub resume_contract: &'static str,
    pub resume_pool: &'static str,
    pub set_farming_contract_id: &'static str,
    pub set_pool_whitelist: &'static str,
    pub set_vip_user: &'static str,
    pub storage_balance_bounds: &'static str,
    pub storage_balance_of: &'static str,
    pub storage_deposit: &'static str,
    pub storage_unregister: &'static str,
    pub storage_withdraw: &'static str,
    pub upgrade: &'static str,
    pub upsert_client_echo_sender_whitelist: &'static str,
    pub upsert_client_echo_token_whitelist: &'static str,
    pub upsert_referral_whitelist: &'static str,
    pub upsert_secure_sender_whitelist: &'static str,
    pub withdraw_asset: &'static str,
}
// =================================================
// =================================================
// copyright 2026 by sleet.near
