// =================================================
/// Method name constants for the house-of-stake voting contract.
pub const HOS_VOTING_METHODS_CONST: HOS_VOTING_METHODS_CONST_TYPE = HOS_VOTING_METHODS_CONST_TYPE {
    accept_ownership: "accept_ownership",
    approve_proposal: "approve_proposal",
    contract_source_metadata: "contract_source_metadata",
    create_proposal: "create_proposal",
    get_approved_proposals: "get_approved_proposals",
    get_config: "get_config",
    get_num_approved_proposals: "get_num_approved_proposals",
    get_num_proposals: "get_num_proposals",
    get_proposal: "get_proposal",
    get_proposals: "get_proposals",
    get_version: "get_version",
    get_vote: "get_vote",
    is_paused: "is_paused",
    migrate_state: "migrate_state",
    new: "new",
    on_get_snapshot: "on_get_snapshot",
    pause: "pause",
    propose_new_owner_account_id: "propose_new_owner_account_id",
    reject_proposal: "reject_proposal",
    set_base_proposal_fee: "set_base_proposal_fee",
    set_guardians: "set_guardians",
    set_max_number_of_voting_options: "set_max_number_of_voting_options",
    set_reviewer_ids: "set_reviewer_ids",
    set_venear_account_id: "set_venear_account_id",
    set_voting_duration: "set_voting_duration",
    unpause: "unpause",
    vote: "vote",
};
// =================================================
/// String constants for hos voting contract method names.
pub struct HOS_VOTING_METHODS_CONST_TYPE {
    pub accept_ownership: &'static str,
    pub approve_proposal: &'static str,
    pub contract_source_metadata: &'static str,
    pub create_proposal: &'static str,
    pub get_approved_proposals: &'static str,
    pub get_config: &'static str,
    pub get_num_approved_proposals: &'static str,
    pub get_num_proposals: &'static str,
    pub get_proposal: &'static str,
    pub get_proposals: &'static str,
    pub get_version: &'static str,
    pub get_vote: &'static str,
    pub is_paused: &'static str,
    pub migrate_state: &'static str,
    pub new: &'static str,
    pub on_get_snapshot: &'static str,
    pub pause: &'static str,
    pub propose_new_owner_account_id: &'static str,
    pub reject_proposal: &'static str,
    pub set_base_proposal_fee: &'static str,
    pub set_guardians: &'static str,
    pub set_max_number_of_voting_options: &'static str,
    pub set_reviewer_ids: &'static str,
    pub set_venear_account_id: &'static str,
    pub set_voting_duration: &'static str,
    pub unpause: &'static str,
    pub vote: &'static str,
}
// =================================================
// =================================================
// copyright 2026 by sleet.near
