// =================================================
/// Method name constants for the rhea / ref-finance contract.
///
/// All 162 methods as reported by `near contract inspect` on
/// `v2.ref-finance.near` (mainnet) and `ref-finance-101.testnet` (testnet).
pub const RHEA_METHODS_CONST: RHEA_METHODS_CONST_TYPE = RHEA_METHODS_CONST_TYPE {
    upgrade: "upgrade",
    register_tokens: "register_tokens",
    unregister_tokens: "unregister_tokens",
    token_register_of: "token_register_of",
    withdraw: "withdraw",
    exchange_callback_post_withdraw_near: "exchange_callback_post_withdraw_near",
    exchange_callback_post_withdraw: "exchange_callback_post_withdraw",
    exchange_callback_post_ft_transfer_call_withdraw: "exchange_callback_post_ft_transfer_call_withdraw",
    get_lostfound_token: "get_lostfound_token",
    list_lostfound_tokens: "list_lostfound_tokens",
    claim_lostfound: "claim_lostfound",
    mft_balance_of: "mft_balance_of",
    mft_total_supply: "mft_total_supply",
    mft_has_registered: "mft_has_registered",
    mft_register: "mft_register",
    mft_unregister: "mft_unregister",
    mft_transfer: "mft_transfer",
    mft_transfer_call: "mft_transfer_call",
    mft_transfer_all_call: "mft_transfer_all_call",
    mft_resolve_transfer: "mft_resolve_transfer",
    mft_metadata: "mft_metadata",
    set_owner: "set_owner",
    get_owner: "get_owner",
    retrieve_unmanaged_token: "retrieve_unmanaged_token",
    extend_guardians: "extend_guardians",
    remove_guardians: "remove_guardians",
    extend_auto_whitelisted_postfix: "extend_auto_whitelisted_postfix",
    remove_auto_whitelisted_postfix: "remove_auto_whitelisted_postfix",
    modify_boost_farm_id: "modify_boost_farm_id",
    modify_burrowland_id: "modify_burrowland_id",
    modify_wnear_id: "modify_wnear_id",
    change_state: "change_state",
    extend_whitelisted_tokens: "extend_whitelisted_tokens",
    remove_whitelisted_tokens: "remove_whitelisted_tokens",
    extend_frozenlist_tokens: "extend_frozenlist_tokens",
    remove_frozenlist_tokens: "remove_frozenlist_tokens",
    insert_referral: "insert_referral",
    update_referral: "update_referral",
    remove_referral: "remove_referral",
    modify_admin_fee: "modify_admin_fee",
    modify_total_fee: "modify_total_fee",
    remove_exchange_fee_liquidity: "remove_exchange_fee_liquidity",
    withdraw_owner_token: "withdraw_owner_token",
    stable_swap_ramp_amp: "stable_swap_ramp_amp",
    stable_swap_stop_ramp_amp: "stable_swap_stop_ramp_amp",
    register_rated_token: "register_rated_token",
    unregister_rated_token: "unregister_rated_token",
    update_rated_token_extra_info: "update_rated_token_extra_info",
    register_degen_token: "register_degen_token",
    update_degen_token: "update_degen_token",
    unregister_degen_token: "unregister_degen_token",
    register_degen_oracle_config: "register_degen_oracle_config",
    unregister_degen_oracle_config: "unregister_degen_oracle_config",
    update_degen_oracle_config: "update_degen_oracle_config",
    add_degen_pool_limit: "add_degen_pool_limit",
    update_degen_pool_limit: "update_degen_pool_limit",
    remove_pool_limit: "remove_pool_limit",
    migrate: "migrate",
    batch_update_degen_token_by_price_oracle_callback: "batch_update_degen_token_by_price_oracle_callback",
    batch_update_degen_token_by_pyth_oracle_callback: "batch_update_degen_token_by_pyth_oracle_callback",
    storage_deposit: "storage_deposit",
    storage_withdraw: "storage_withdraw",
    storage_unregister: "storage_unregister",
    storage_balance_bounds: "storage_balance_bounds",
    storage_balance_of: "storage_balance_of",
    ft_on_transfer: "ft_on_transfer",
    metadata: "metadata",
    get_guardians: "get_guardians",
    version: "version",
    get_number_of_pools: "get_number_of_pools",
    get_pools: "get_pools",
    get_pool: "get_pool",
    get_pool_by_ids: "get_pool_by_ids",
    get_pool_detail_infos: "get_pool_detail_infos",
    get_pool_detail_info: "get_pool_detail_info",
    get_pool_detail_info_by_ids: "get_pool_detail_info_by_ids",
    get_stable_pool: "get_stable_pool",
    get_rated_pool: "get_rated_pool",
    get_degen_pool: "get_degen_pool",
    get_pool_fee: "get_pool_fee",
    get_pool_volumes: "get_pool_volumes",
    get_pool_volumes_by_ids: "get_pool_volumes_by_ids",
    list_pool_volumes: "list_pool_volumes",
    get_pool_share_price: "get_pool_share_price",
    get_pool_shares: "get_pool_shares",
    get_pool_shares_batch: "get_pool_shares_batch",
    get_pool_total_shares: "get_pool_total_shares",
    get_deposits: "get_deposits",
    get_tokens_paged: "get_tokens_paged",
    get_account_basic_info: "get_account_basic_info",
    get_shadow_records: "get_shadow_records",
    get_deposit: "get_deposit",
    get_return: "get_return",
    get_return_by_output: "get_return_by_output",
    list_referrals: "list_referrals",
    get_frozenlist_tokens: "get_frozenlist_tokens",
    get_whitelisted_tokens: "get_whitelisted_tokens",
    get_user_whitelisted_tokens: "get_user_whitelisted_tokens",
    get_user_storage_state: "get_user_storage_state",
    predict_add_simple_liquidity: "predict_add_simple_liquidity",
    predict_add_stable_liquidity: "predict_add_stable_liquidity",
    predict_remove_liquidity: "predict_remove_liquidity",
    predict_remove_liquidity_by_tokens: "predict_remove_liquidity_by_tokens",
    list_rated_tokens: "list_rated_tokens",
    batch_get_degen_tokens: "batch_get_degen_tokens",
    list_degen_tokens: "list_degen_tokens",
    list_degen_oracle_configs: "list_degen_oracle_configs",
    predict_add_rated_liquidity: "predict_add_rated_liquidity",
    predict_add_degen_liquidity: "predict_add_degen_liquidity",
    predict_remove_rated_liquidity_by_tokens: "predict_remove_rated_liquidity_by_tokens",
    predict_remove_degen_liquidity_by_tokens: "predict_remove_degen_liquidity_by_tokens",
    get_rated_return: "get_rated_return",
    get_degen_return: "get_degen_return",
    predict_swap_actions: "predict_swap_actions",
    batch_predict_swap_actions: "batch_predict_swap_actions",
    predict_hot_zap: "predict_hot_zap",
    get_degen_pool_tvl: "get_degen_pool_tvl",
    get_pool_limit_by_pool_id: "get_pool_limit_by_pool_id",
    get_pool_limit_paged: "get_pool_limit_paged",
    batch_views: "batch_views",
    get_unit_lpt_assets: "get_unit_lpt_assets",
    shadow_action: "shadow_action",
    on_burrow_liquidation: "on_burrow_liquidation",
    callback_on_shadow: "callback_on_shadow",
    callback_on_burrow_liquidation: "callback_on_burrow_liquidation",
    register_pool_twap_record: "register_pool_twap_record",
    unregister_pool_twap_record: "unregister_pool_twap_record",
    modify_cumulative_info_record_interval_sec: "modify_cumulative_info_record_interval_sec",
    sync_pool_twap_record: "sync_pool_twap_record",
    get_pool_twap_info_view: "get_pool_twap_info_view",
    list_pool_twap_info_view: "list_pool_twap_info_view",
    get_unit_share_twap_token_amounts: "get_unit_share_twap_token_amounts",
    get_unit_share_token_amounts: "get_unit_share_token_amounts",
    extend_client_echo_token_id_whitelist: "extend_client_echo_token_id_whitelist",
    remove_client_echo_token_id_whitelist: "remove_client_echo_token_id_whitelist",
    get_client_echo_token_id_whitelist: "get_client_echo_token_id_whitelist",
    extend_client_echo_sender_id_whitelist: "extend_client_echo_sender_id_whitelist",
    remove_client_echo_sender_id_whitelist: "remove_client_echo_sender_id_whitelist",
    get_client_echo_sender_id_whitelist: "get_client_echo_sender_id_whitelist",
    extend_secure_sender_whitelist: "extend_secure_sender_whitelist",
    remove_secure_sender_whitelist: "remove_secure_sender_whitelist",
    get_secure_sender_whitelist: "get_secure_sender_whitelist",
    donation_share: "donation_share",
    donation_token: "donation_token",
    new: "new",
    add_simple_pool: "add_simple_pool",
    add_stable_swap_pool: "add_stable_swap_pool",
    add_rated_swap_pool: "add_rated_swap_pool",
    add_degen_swap_pool: "add_degen_swap_pool",
    execute_actions_in_va: "execute_actions_in_va",
    execute_actions: "execute_actions",
    swap: "swap",
    swap_by_output: "swap_by_output",
    add_liquidity: "add_liquidity",
    add_stable_liquidity: "add_stable_liquidity",
    remove_liquidity: "remove_liquidity",
    remove_liquidity_by_tokens: "remove_liquidity_by_tokens",
    update_token_rate: "update_token_rate",
    update_token_rate_callback: "update_token_rate_callback",
    batch_update_degen_token_price: "batch_update_degen_token_price",
    update_degen_token_price: "update_degen_token_price",
    update_degen_token_price_callback: "update_degen_token_price_callback",
};
// =================================================
/// String constants for rhea / ref-finance contract method names.
pub struct RHEA_METHODS_CONST_TYPE {
    pub upgrade: &'static str,
    pub register_tokens: &'static str,
    pub unregister_tokens: &'static str,
    pub token_register_of: &'static str,
    pub withdraw: &'static str,
    pub exchange_callback_post_withdraw_near: &'static str,
    pub exchange_callback_post_withdraw: &'static str,
    pub exchange_callback_post_ft_transfer_call_withdraw: &'static str,
    pub get_lostfound_token: &'static str,
    pub list_lostfound_tokens: &'static str,
    pub claim_lostfound: &'static str,
    pub mft_balance_of: &'static str,
    pub mft_total_supply: &'static str,
    pub mft_has_registered: &'static str,
    pub mft_register: &'static str,
    pub mft_unregister: &'static str,
    pub mft_transfer: &'static str,
    pub mft_transfer_call: &'static str,
    pub mft_transfer_all_call: &'static str,
    pub mft_resolve_transfer: &'static str,
    pub mft_metadata: &'static str,
    pub set_owner: &'static str,
    pub get_owner: &'static str,
    pub retrieve_unmanaged_token: &'static str,
    pub extend_guardians: &'static str,
    pub remove_guardians: &'static str,
    pub extend_auto_whitelisted_postfix: &'static str,
    pub remove_auto_whitelisted_postfix: &'static str,
    pub modify_boost_farm_id: &'static str,
    pub modify_burrowland_id: &'static str,
    pub modify_wnear_id: &'static str,
    pub change_state: &'static str,
    pub extend_whitelisted_tokens: &'static str,
    pub remove_whitelisted_tokens: &'static str,
    pub extend_frozenlist_tokens: &'static str,
    pub remove_frozenlist_tokens: &'static str,
    pub insert_referral: &'static str,
    pub update_referral: &'static str,
    pub remove_referral: &'static str,
    pub modify_admin_fee: &'static str,
    pub modify_total_fee: &'static str,
    pub remove_exchange_fee_liquidity: &'static str,
    pub withdraw_owner_token: &'static str,
    pub stable_swap_ramp_amp: &'static str,
    pub stable_swap_stop_ramp_amp: &'static str,
    pub register_rated_token: &'static str,
    pub unregister_rated_token: &'static str,
    pub update_rated_token_extra_info: &'static str,
    pub register_degen_token: &'static str,
    pub update_degen_token: &'static str,
    pub unregister_degen_token: &'static str,
    pub register_degen_oracle_config: &'static str,
    pub unregister_degen_oracle_config: &'static str,
    pub update_degen_oracle_config: &'static str,
    pub add_degen_pool_limit: &'static str,
    pub update_degen_pool_limit: &'static str,
    pub remove_pool_limit: &'static str,
    pub migrate: &'static str,
    pub batch_update_degen_token_by_price_oracle_callback: &'static str,
    pub batch_update_degen_token_by_pyth_oracle_callback: &'static str,
    pub storage_deposit: &'static str,
    pub storage_withdraw: &'static str,
    pub storage_unregister: &'static str,
    pub storage_balance_bounds: &'static str,
    pub storage_balance_of: &'static str,
    pub ft_on_transfer: &'static str,
    pub metadata: &'static str,
    pub get_guardians: &'static str,
    pub version: &'static str,
    pub get_number_of_pools: &'static str,
    pub get_pools: &'static str,
    pub get_pool: &'static str,
    pub get_pool_by_ids: &'static str,
    pub get_pool_detail_infos: &'static str,
    pub get_pool_detail_info: &'static str,
    pub get_pool_detail_info_by_ids: &'static str,
    pub get_stable_pool: &'static str,
    pub get_rated_pool: &'static str,
    pub get_degen_pool: &'static str,
    pub get_pool_fee: &'static str,
    pub get_pool_volumes: &'static str,
    pub get_pool_volumes_by_ids: &'static str,
    pub list_pool_volumes: &'static str,
    pub get_pool_share_price: &'static str,
    pub get_pool_shares: &'static str,
    pub get_pool_shares_batch: &'static str,
    pub get_pool_total_shares: &'static str,
    pub get_deposits: &'static str,
    pub get_tokens_paged: &'static str,
    pub get_account_basic_info: &'static str,
    pub get_shadow_records: &'static str,
    pub get_deposit: &'static str,
    pub get_return: &'static str,
    pub get_return_by_output: &'static str,
    pub list_referrals: &'static str,
    pub get_frozenlist_tokens: &'static str,
    pub get_whitelisted_tokens: &'static str,
    pub get_user_whitelisted_tokens: &'static str,
    pub get_user_storage_state: &'static str,
    pub predict_add_simple_liquidity: &'static str,
    pub predict_add_stable_liquidity: &'static str,
    pub predict_remove_liquidity: &'static str,
    pub predict_remove_liquidity_by_tokens: &'static str,
    pub list_rated_tokens: &'static str,
    pub batch_get_degen_tokens: &'static str,
    pub list_degen_tokens: &'static str,
    pub list_degen_oracle_configs: &'static str,
    pub predict_add_rated_liquidity: &'static str,
    pub predict_add_degen_liquidity: &'static str,
    pub predict_remove_rated_liquidity_by_tokens: &'static str,
    pub predict_remove_degen_liquidity_by_tokens: &'static str,
    pub get_rated_return: &'static str,
    pub get_degen_return: &'static str,
    pub predict_swap_actions: &'static str,
    pub batch_predict_swap_actions: &'static str,
    pub predict_hot_zap: &'static str,
    pub get_degen_pool_tvl: &'static str,
    pub get_pool_limit_by_pool_id: &'static str,
    pub get_pool_limit_paged: &'static str,
    pub batch_views: &'static str,
    pub get_unit_lpt_assets: &'static str,
    pub shadow_action: &'static str,
    pub on_burrow_liquidation: &'static str,
    pub callback_on_shadow: &'static str,
    pub callback_on_burrow_liquidation: &'static str,
    pub register_pool_twap_record: &'static str,
    pub unregister_pool_twap_record: &'static str,
    pub modify_cumulative_info_record_interval_sec: &'static str,
    pub sync_pool_twap_record: &'static str,
    pub get_pool_twap_info_view: &'static str,
    pub list_pool_twap_info_view: &'static str,
    pub get_unit_share_twap_token_amounts: &'static str,
    pub get_unit_share_token_amounts: &'static str,
    pub extend_client_echo_token_id_whitelist: &'static str,
    pub remove_client_echo_token_id_whitelist: &'static str,
    pub get_client_echo_token_id_whitelist: &'static str,
    pub extend_client_echo_sender_id_whitelist: &'static str,
    pub remove_client_echo_sender_id_whitelist: &'static str,
    pub get_client_echo_sender_id_whitelist: &'static str,
    pub extend_secure_sender_whitelist: &'static str,
    pub remove_secure_sender_whitelist: &'static str,
    pub get_secure_sender_whitelist: &'static str,
    pub donation_share: &'static str,
    pub donation_token: &'static str,
    pub new: &'static str,
    pub add_simple_pool: &'static str,
    pub add_stable_swap_pool: &'static str,
    pub add_rated_swap_pool: &'static str,
    pub add_degen_swap_pool: &'static str,
    pub execute_actions_in_va: &'static str,
    pub execute_actions: &'static str,
    pub swap: &'static str,
    pub swap_by_output: &'static str,
    pub add_liquidity: &'static str,
    pub add_stable_liquidity: &'static str,
    pub remove_liquidity: &'static str,
    pub remove_liquidity_by_tokens: &'static str,
    pub update_token_rate: &'static str,
    pub update_token_rate_callback: &'static str,
    pub batch_update_degen_token_price: &'static str,
    pub update_degen_token_price: &'static str,
    pub update_degen_token_price_callback: &'static str,
}
// =================================================
// =================================================
// copyright 2026 by sleet.near
