// =================================================
/// Method name constants for the app.chess-game.near contract.
pub const CHESS_GAME_METHODS_CONST: CHESS_GAME_METHODS_CONST_TYPE = CHESS_GAME_METHODS_CONST_TYPE {
    ft_on_transfer: "ft_on_transfer",
    ft_metadata: "ft_metadata",
    ft_transfer: "ft_transfer",
    ft_transfer_call: "ft_transfer_call",
    ft_total_supply: "ft_total_supply",
    ft_balance_of: "ft_balance_of",
    storage_deposit: "storage_deposit",
    storage_withdraw: "storage_withdraw",
    storage_unregister: "storage_unregister",
    storage_balance_bounds: "storage_balance_bounds",
    storage_balance_of: "storage_balance_of",
    get_board: "get_board",
    render_board: "render_board",
    game_info: "game_info",
    bet_info: "bet_info",
    get_game_ids: "get_game_ids",
    get_account: "get_account",
    get_quest_list: "get_quest_list",
    get_quest_cooldowns: "get_quest_cooldowns",
    get_achievement_list: "get_achievement_list",
    get_achievements: "get_achievements",
    get_tokens: "get_tokens",
    get_token_amount: "get_token_amount",
    get_elo_ratings: "get_elo_ratings",
    get_elo_ratings_by_ids: "get_elo_ratings_by_ids",
    get_ppp_balances_by_ids: "get_ppp_balances_by_ids",
    get_accounts: "get_accounts",
    get_challenge: "get_challenge",
    get_challenges: "get_challenges",
    get_treasury_tokens: "get_treasury_tokens",
    get_fees: "get_fees",
    get_token_whitelist: "get_token_whitelist",
    get_owner: "get_owner",
    is_queued: "is_queued",
    get_matchmaking_queue: "get_matchmaking_queue",
    contract_source_metadata: "contract_source_metadata",
    new: "new",
    migrate: "migrate",
    pause: "pause",
    set_is_agent: "set_is_agent",
    resume: "resume",
    set_fees: "set_fees",
    set_token_whitelist: "set_token_whitelist",
    withdraw_treasury: "withdraw_treasury",
    withdraw_treasury_callback: "withdraw_treasury_callback",
    transfer_ownership: "transfer_ownership",
    create_ai_game: "create_ai_game",
    challenge: "challenge",
    accept_challenge: "accept_challenge",
    reject_challenge: "reject_challenge",
    reject_challenge_wager_callback: "reject_challenge_wager_callback",
    claim_points: "claim_points",
    join_matchmaking: "join_matchmaking",
    cancel_matchmaking: "cancel_matchmaking",
    play_move: "play_move",
    resign: "resign",
    cancel: "cancel",
    cancel_wager_refund_callback: "cancel_wager_refund_callback",
    wager_victory_callback: "wager_victory_callback",
    wager_stalemate_callback: "wager_stalemate_callback",
    cancel_bet: "cancel_bet",
    withdraw_token: "withdraw_token",
    withdraw_token_callback: "withdraw_token_callback",
};
// =================================================
/// String constants for app.chess-game.near contract method names.
pub struct CHESS_GAME_METHODS_CONST_TYPE {
    pub ft_on_transfer: &'static str,
    pub ft_metadata: &'static str,
    pub ft_transfer: &'static str,
    pub ft_transfer_call: &'static str,
    pub ft_total_supply: &'static str,
    pub ft_balance_of: &'static str,
    pub storage_deposit: &'static str,
    pub storage_withdraw: &'static str,
    pub storage_unregister: &'static str,
    pub storage_balance_bounds: &'static str,
    pub storage_balance_of: &'static str,
    pub get_board: &'static str,
    pub render_board: &'static str,
    pub game_info: &'static str,
    pub bet_info: &'static str,
    pub get_game_ids: &'static str,
    pub get_account: &'static str,
    pub get_quest_list: &'static str,
    pub get_quest_cooldowns: &'static str,
    pub get_achievement_list: &'static str,
    pub get_achievements: &'static str,
    pub get_tokens: &'static str,
    pub get_token_amount: &'static str,
    pub get_elo_ratings: &'static str,
    pub get_elo_ratings_by_ids: &'static str,
    pub get_ppp_balances_by_ids: &'static str,
    pub get_accounts: &'static str,
    pub get_challenge: &'static str,
    pub get_challenges: &'static str,
    pub get_treasury_tokens: &'static str,
    pub get_fees: &'static str,
    pub get_token_whitelist: &'static str,
    pub get_owner: &'static str,
    pub is_queued: &'static str,
    pub get_matchmaking_queue: &'static str,
    pub contract_source_metadata: &'static str,
    pub new: &'static str,
    pub migrate: &'static str,
    pub pause: &'static str,
    pub set_is_agent: &'static str,
    pub resume: &'static str,
    pub set_fees: &'static str,
    pub set_token_whitelist: &'static str,
    pub withdraw_treasury: &'static str,
    pub withdraw_treasury_callback: &'static str,
    pub transfer_ownership: &'static str,
    pub create_ai_game: &'static str,
    pub challenge: &'static str,
    pub accept_challenge: &'static str,
    pub reject_challenge: &'static str,
    pub reject_challenge_wager_callback: &'static str,
    pub claim_points: &'static str,
    pub join_matchmaking: &'static str,
    pub cancel_matchmaking: &'static str,
    pub play_move: &'static str,
    pub resign: &'static str,
    pub cancel: &'static str,
    pub cancel_wager_refund_callback: &'static str,
    pub wager_victory_callback: &'static str,
    pub wager_stalemate_callback: &'static str,
    pub cancel_bet: &'static str,
    pub withdraw_token: &'static str,
    pub withdraw_token_callback: &'static str,
}
// =================================================
// =================================================
// copyright 2026 by sleet.near
