// =================================================
/// Method name constants for the standard staking-pool contract
/// (`code_hash`: `AjD4YJaXgpiRdiArqnzyDi7Bkr1gJms9Z2w7Ev5esTKB`).
///
/// This is the v2 staking pool — a child contract deployed by the
/// `pool.near` factory. Each pool has its own account id, so no global
/// contract-id const is provided.
pub const POOL_STAKING_METHODS_CONST: POOL_STAKING_METHODS_CONST_TYPE =
    POOL_STAKING_METHODS_CONST_TYPE {
        upgrade: "upgrade",
        update: "update",
        migrate: "migrate",
        callback_post_get_owner: "callback_post_get_owner",
        callback_post_withdraw_reward: "callback_post_withdraw_reward",
        claim: "claim",
        stop_farm: "stop_farm",
        set_owner_id: "set_owner_id",
        update_staking_key: "update_staking_key",
        update_reward_fee_fraction: "update_reward_fee_fraction",
        decrease_burn_fee_fraction: "decrease_burn_fee_fraction",
        pause_staking: "pause_staking",
        resume_staking: "resume_staking",
        add_authorized_user: "add_authorized_user",
        remove_authorized_user: "remove_authorized_user",
        add_authorized_farm_token: "add_authorized_farm_token",
        remove_authorized_farm_token: "remove_authorized_farm_token",
        deposit: "deposit",
        deposit_and_stake: "deposit_and_stake",
        withdraw_all: "withdraw_all",
        withdraw: "withdraw",
        stake_all: "stake_all",
        stake: "stake",
        unstake_all: "unstake_all",
        unstake: "unstake",
        unstake_burn: "unstake_burn",
        burn: "burn",
        on_stake_action: "on_stake_action",
        ft_on_transfer: "ft_on_transfer",
        get_pool_summary: "get_pool_summary",
        get_version: "get_version",
        get_owner_id: "get_owner_id",
        get_factory_id: "get_factory_id",
        get_authorized_users: "get_authorized_users",
        get_authorized_farm_tokens: "get_authorized_farm_tokens",
        get_active_farms: "get_active_farms",
        get_farms: "get_farms",
        get_farm: "get_farm",
        get_unclaimed_reward: "get_unclaimed_reward",
        get_account_unstaked_balance: "get_account_unstaked_balance",
        get_account_staked_balance: "get_account_staked_balance",
        get_account_total_balance: "get_account_total_balance",
        is_account_unstaked_balance_available: "is_account_unstaked_balance_available",
        get_total_staked_balance: "get_total_staked_balance",
        get_reward_fee_fraction: "get_reward_fee_fraction",
        get_staking_key: "get_staking_key",
        is_staking_paused: "is_staking_paused",
        get_account: "get_account",
        get_number_of_accounts: "get_number_of_accounts",
        get_accounts: "get_accounts",
        new: "new",
        ping: "ping",
    };
// =================================================
/// String constants for the standard staking-pool contract method names.
pub struct POOL_STAKING_METHODS_CONST_TYPE {
    pub upgrade: &'static str,
    pub update: &'static str,
    pub migrate: &'static str,
    pub callback_post_get_owner: &'static str,
    pub callback_post_withdraw_reward: &'static str,
    pub claim: &'static str,
    pub stop_farm: &'static str,
    pub set_owner_id: &'static str,
    pub update_staking_key: &'static str,
    pub update_reward_fee_fraction: &'static str,
    pub decrease_burn_fee_fraction: &'static str,
    pub pause_staking: &'static str,
    pub resume_staking: &'static str,
    pub add_authorized_user: &'static str,
    pub remove_authorized_user: &'static str,
    pub add_authorized_farm_token: &'static str,
    pub remove_authorized_farm_token: &'static str,
    pub deposit: &'static str,
    pub deposit_and_stake: &'static str,
    pub withdraw_all: &'static str,
    pub withdraw: &'static str,
    pub stake_all: &'static str,
    pub stake: &'static str,
    pub unstake_all: &'static str,
    pub unstake: &'static str,
    pub unstake_burn: &'static str,
    pub burn: &'static str,
    pub on_stake_action: &'static str,
    pub ft_on_transfer: &'static str,
    pub get_pool_summary: &'static str,
    pub get_version: &'static str,
    pub get_owner_id: &'static str,
    pub get_factory_id: &'static str,
    pub get_authorized_users: &'static str,
    pub get_authorized_farm_tokens: &'static str,
    pub get_active_farms: &'static str,
    pub get_farms: &'static str,
    pub get_farm: &'static str,
    pub get_unclaimed_reward: &'static str,
    pub get_account_unstaked_balance: &'static str,
    pub get_account_staked_balance: &'static str,
    pub get_account_total_balance: &'static str,
    pub is_account_unstaked_balance_available: &'static str,
    pub get_total_staked_balance: &'static str,
    pub get_reward_fee_fraction: &'static str,
    pub get_staking_key: &'static str,
    pub is_staking_paused: &'static str,
    pub get_account: &'static str,
    pub get_number_of_accounts: &'static str,
    pub get_accounts: &'static str,
    pub new: &'static str,
    pub ping: &'static str,
}
// =================================================
// =================================================
// copyright 2026 by sleet.near
