// =================================================
/// Method name constants for the berryclub.ek.near draw-to-earn pixel game.
pub const BERRYCLUB_METHODS_CONST: BERRYCLUB_METHODS_CONST_TYPE = BERRYCLUB_METHODS_CONST_TYPE {
    get_pixel_cost: "get_pixel_cost",
    get_account_by_index: "get_account_by_index",
    get_account: "get_account",
    get_account_balance: "get_account_balance",
    get_account_num_pixels: "get_account_num_pixels",
    get_account_id_by_index: "get_account_id_by_index",
    get_lines: "get_lines",
    get_line_versions: "get_line_versions",
    ft_transfer: "ft_transfer",
    ft_transfer_call: "ft_transfer_call",
    ft_total_supply: "ft_total_supply",
    ft_balance_of: "ft_balance_of",
    ft_resolve_transfer: "ft_resolve_transfer",
    ft_metadata: "ft_metadata",
    storage_deposit: "storage_deposit",
    storage_withdraw: "storage_withdraw",
    storage_unregister: "storage_unregister",
    storage_balance_bounds: "storage_balance_bounds",
    storage_balance_of: "storage_balance_of",
    transfer_raw: "transfer_raw",
    transfer_with_vault: "transfer_with_vault",
    withdraw_from_vault: "withdraw_from_vault",
    resolve_vault: "resolve_vault",
    get_total_supply: "get_total_supply",
    get_balance: "get_balance",
    new: "new",
    register_account: "register_account",
    account_exists: "account_exists",
    buy_tokens: "buy_tokens",
    select_farming_preference: "select_farming_preference",
    get_free_drawing_timestamp: "get_free_drawing_timestamp",
    draw: "draw",
    get_num_accounts: "get_num_accounts",
    get_last_reward_timestamp: "get_last_reward_timestamp",
    get_next_reward_timestamp: "get_next_reward_timestamp",
    get_expected_reward: "get_expected_reward",
    stats: "stats",
};
// =================================================
/// String constants for berryclub contract method names.
pub struct BERRYCLUB_METHODS_CONST_TYPE {
    pub get_pixel_cost: &'static str,
    pub get_account_by_index: &'static str,
    pub get_account: &'static str,
    pub get_account_balance: &'static str,
    pub get_account_num_pixels: &'static str,
    pub get_account_id_by_index: &'static str,
    pub get_lines: &'static str,
    pub get_line_versions: &'static str,
    pub ft_transfer: &'static str,
    pub ft_transfer_call: &'static str,
    pub ft_total_supply: &'static str,
    pub ft_balance_of: &'static str,
    pub ft_resolve_transfer: &'static str,
    pub ft_metadata: &'static str,
    pub storage_deposit: &'static str,
    pub storage_withdraw: &'static str,
    pub storage_unregister: &'static str,
    pub storage_balance_bounds: &'static str,
    pub storage_balance_of: &'static str,
    pub transfer_raw: &'static str,
    pub transfer_with_vault: &'static str,
    pub withdraw_from_vault: &'static str,
    pub resolve_vault: &'static str,
    pub get_total_supply: &'static str,
    pub get_balance: &'static str,
    pub new: &'static str,
    pub register_account: &'static str,
    pub account_exists: &'static str,
    pub buy_tokens: &'static str,
    pub select_farming_preference: &'static str,
    pub get_free_drawing_timestamp: &'static str,
    pub draw: &'static str,
    pub get_num_accounts: &'static str,
    pub get_last_reward_timestamp: &'static str,
    pub get_next_reward_timestamp: &'static str,
    pub get_expected_reward: &'static str,
    pub stats: &'static str,
}
// =================================================
// =================================================
// copyright 2026 by sleet.near