// =================================================
/// Method name constants for the meta-pool.near stNEAR liquid-staking contract.
pub const META_POOL_METHODS_CONST: META_POOL_METHODS_CONST_TYPE = META_POOL_METHODS_CONST_TYPE {
    distribute_staking: "distribute_staking",
    on_staking_pool_stake_maybe_deposit: "on_staking_pool_stake_maybe_deposit",
    manual_stake: "manual_stake",
    force_rebalance_unstake: "force_rebalance_unstake",
    rebalance_unstake_sp: "rebalance_unstake_sp",
    do_rebalance_unstake: "do_rebalance_unstake",
    distribute_unstaking: "distribute_unstaking",
    on_staking_pool_unstake: "on_staking_pool_unstake",
    set_busy: "set_busy",
    sp_busy: "sp_busy",
    extra_balance_accumulated: "extra_balance_accumulated",
    transfer_extra_balance_accumulated: "transfer_extra_balance_accumulated",
    sync_unstaked_balance: "sync_unstaked_balance",
    on_get_sp_unstaked_balance: "on_get_sp_unstaked_balance",
    distribute_rewards: "distribute_rewards",
    on_get_sp_total_balance: "on_get_sp_total_balance",
    get_staking_pool_requiring_retrieve: "get_staking_pool_requiring_retrieve",
    retrieve_funds_from_a_pool: "retrieve_funds_from_a_pool",
    on_retrieve_from_staking_pool: "on_retrieve_from_staking_pool",
    end_of_epoch_clearing: "end_of_epoch_clearing",
    migrate: "migrate",
    pause_staking: "pause_staking",
    un_pause_staking: "un_pause_staking",
    get_staking_pool_list: "get_staking_pool_list",
    remove_staking_pool: "remove_staking_pool",
    add_staking_pool: "add_staking_pool",
    set_staking_pools: "set_staking_pools",
    compute_current_unstaking_delay: "compute_current_unstaking_delay",
    get_operator_account_id: "get_operator_account_id",
    set_operator_account_id: "set_operator_account_id",
    get_treasury_account_id: "get_treasury_account_id",
    set_treasury_account_id: "set_treasury_account_id",
    set_owner_id: "set_owner_id",
    get_known_deposited_balance: "get_known_deposited_balance",
    get_account_info: "get_account_info",
    get_contract_info: "get_contract_info",
    set_contract_info: "set_contract_info",
    get_st_near_price: "get_st_near_price",
    get_contract_state: "get_contract_state",
    get_contract_params: "get_contract_params",
    set_contract_params: "set_contract_params",
    set_reward_multipliers: "set_reward_multipliers",
    set_max_meta_rewards: "set_max_meta_rewards",
    get_sp_info: "get_sp_info",
    get_staking_pool_requiring_unstake: "get_staking_pool_requiring_unstake",
    storage_deposit: "storage_deposit",
    storage_withdraw: "storage_withdraw",
    storage_unregister: "storage_unregister",
    storage_balance_bounds: "storage_balance_bounds",
    storage_balance_of: "storage_balance_of",
    ft_transfer: "ft_transfer",
    ft_transfer_call: "ft_transfer_call",
    ft_total_supply: "ft_total_supply",
    ft_balance_of: "ft_balance_of",
    ft_resolve_transfer: "ft_resolve_transfer",
    ft_metadata: "ft_metadata",
    ft_metadata_set: "ft_metadata_set",
    new: "new",
    ping: "ping",
    deposit: "deposit",
    withdraw: "withdraw",
    withdraw_all: "withdraw_all",
    withdraw_unstaked: "withdraw_unstaked",
    deposit_and_stake: "deposit_and_stake",
    stake_all: "stake_all",
    stake: "stake",
    unstake_all: "unstake_all",
    unstake: "unstake",
    stake_for_lockup: "stake_for_lockup",
    unstake_from_lockup_shares: "unstake_from_lockup_shares",
    withdraw_to_lockup: "withdraw_to_lockup",
    get_account_unstaked_balance: "get_account_unstaked_balance",
    get_account_staked_balance: "get_account_staked_balance",
    get_account_total_balance: "get_account_total_balance",
    get_account_available_balance: "get_account_available_balance",
    is_account_unstaked_balance_available: "is_account_unstaked_balance_available",
    get_owner_id: "get_owner_id",
    get_reward_fee_fraction: "get_reward_fee_fraction",
    get_reward_fee_bp: "get_reward_fee_bp",
    set_reward_fee: "set_reward_fee",
    get_staking_key: "get_staking_key",
    is_staking_paused: "is_staking_paused",
    get_account: "get_account",
    get_number_of_accounts: "get_number_of_accounts",
    get_accounts: "get_accounts",
    get_accounts_info: "get_accounts_info",
    get_near_amount_sell_stnear: "get_near_amount_sell_stnear",
    nslp_get_discount_basis_points: "nslp_get_discount_basis_points",
    liquid_unstake: "liquid_unstake",
    nslp_add_liquidity: "nslp_add_liquidity",
    nslp_remove_liquidity: "nslp_remove_liquidity",
    stake_from_nslp: "stake_from_nslp",
    realize_meta: "realize_meta",
    harvest_meta: "harvest_meta",
    upgrade: "upgrade",
};
// =================================================
/// String constants for meta-pool.near contract method names.
pub struct META_POOL_METHODS_CONST_TYPE {
    pub distribute_staking: &'static str,
    pub on_staking_pool_stake_maybe_deposit: &'static str,
    pub manual_stake: &'static str,
    pub force_rebalance_unstake: &'static str,
    pub rebalance_unstake_sp: &'static str,
    pub do_rebalance_unstake: &'static str,
    pub distribute_unstaking: &'static str,
    pub on_staking_pool_unstake: &'static str,
    pub set_busy: &'static str,
    pub sp_busy: &'static str,
    pub extra_balance_accumulated: &'static str,
    pub transfer_extra_balance_accumulated: &'static str,
    pub sync_unstaked_balance: &'static str,
    pub on_get_sp_unstaked_balance: &'static str,
    pub distribute_rewards: &'static str,
    pub on_get_sp_total_balance: &'static str,
    pub get_staking_pool_requiring_retrieve: &'static str,
    pub retrieve_funds_from_a_pool: &'static str,
    pub on_retrieve_from_staking_pool: &'static str,
    pub end_of_epoch_clearing: &'static str,
    pub migrate: &'static str,
    pub pause_staking: &'static str,
    pub un_pause_staking: &'static str,
    pub get_staking_pool_list: &'static str,
    pub remove_staking_pool: &'static str,
    pub add_staking_pool: &'static str,
    pub set_staking_pools: &'static str,
    pub compute_current_unstaking_delay: &'static str,
    pub get_operator_account_id: &'static str,
    pub set_operator_account_id: &'static str,
    pub get_treasury_account_id: &'static str,
    pub set_treasury_account_id: &'static str,
    pub set_owner_id: &'static str,
    pub get_known_deposited_balance: &'static str,
    pub get_account_info: &'static str,
    pub get_contract_info: &'static str,
    pub set_contract_info: &'static str,
    pub get_st_near_price: &'static str,
    pub get_contract_state: &'static str,
    pub get_contract_params: &'static str,
    pub set_contract_params: &'static str,
    pub set_reward_multipliers: &'static str,
    pub set_max_meta_rewards: &'static str,
    pub get_sp_info: &'static str,
    pub get_staking_pool_requiring_unstake: &'static str,
    pub storage_deposit: &'static str,
    pub storage_withdraw: &'static str,
    pub storage_unregister: &'static str,
    pub storage_balance_bounds: &'static str,
    pub storage_balance_of: &'static str,
    pub ft_transfer: &'static str,
    pub ft_transfer_call: &'static str,
    pub ft_total_supply: &'static str,
    pub ft_balance_of: &'static str,
    pub ft_resolve_transfer: &'static str,
    pub ft_metadata: &'static str,
    pub ft_metadata_set: &'static str,
    pub new: &'static str,
    pub ping: &'static str,
    pub deposit: &'static str,
    pub withdraw: &'static str,
    pub withdraw_all: &'static str,
    pub withdraw_unstaked: &'static str,
    pub deposit_and_stake: &'static str,
    pub stake_all: &'static str,
    pub stake: &'static str,
    pub unstake_all: &'static str,
    pub unstake: &'static str,
    pub stake_for_lockup: &'static str,
    pub unstake_from_lockup_shares: &'static str,
    pub withdraw_to_lockup: &'static str,
    pub get_account_unstaked_balance: &'static str,
    pub get_account_staked_balance: &'static str,
    pub get_account_total_balance: &'static str,
    pub get_account_available_balance: &'static str,
    pub is_account_unstaked_balance_available: &'static str,
    pub get_owner_id: &'static str,
    pub get_reward_fee_fraction: &'static str,
    pub get_reward_fee_bp: &'static str,
    pub set_reward_fee: &'static str,
    pub get_staking_key: &'static str,
    pub is_staking_paused: &'static str,
    pub get_account: &'static str,
    pub get_number_of_accounts: &'static str,
    pub get_accounts: &'static str,
    pub get_accounts_info: &'static str,
    pub get_near_amount_sell_stnear: &'static str,
    pub nslp_get_discount_basis_points: &'static str,
    pub liquid_unstake: &'static str,
    pub nslp_add_liquidity: &'static str,
    pub nslp_remove_liquidity: &'static str,
    pub stake_from_nslp: &'static str,
    pub realize_meta: &'static str,
    pub harvest_meta: &'static str,
    pub upgrade: &'static str,
}
// =================================================
// =================================================
// copyright 2026 by sleet.near