// =================================================
/// Method name constants for the house-of-stake venear (governance token) contract.
pub const HOS_VENEAR_METHODS_CONST: HOS_VENEAR_METHODS_CONST_TYPE = HOS_VENEAR_METHODS_CONST_TYPE {
    accept_ownership: "accept_ownership",
    contract_source_metadata: "contract_source_metadata",
    delegate_all: "delegate_all",
    deploy_lockup: "deploy_lockup",
    ft_balance_of: "ft_balance_of",
    ft_metadata: "ft_metadata",
    ft_total_supply: "ft_total_supply",
    ft_transfer: "ft_transfer",
    ft_transfer_call: "ft_transfer_call",
    get_account_by_index: "get_account_by_index",
    get_account_info: "get_account_info",
    get_accounts: "get_accounts",
    get_accounts_raw: "get_accounts_raw",
    get_config: "get_config",
    get_lockup_account_id: "get_lockup_account_id",
    get_lockup_deployment_cost: "get_lockup_deployment_cost",
    get_num_accounts: "get_num_accounts",
    get_proof: "get_proof",
    get_snapshot: "get_snapshot",
    get_version: "get_version",
    is_paused: "is_paused",
    migrate_state: "migrate_state",
    new: "new",
    on_lockup_deployed: "on_lockup_deployed",
    on_lockup_update: "on_lockup_update",
    pause: "pause",
    propose_new_owner_account_id: "propose_new_owner_account_id",
    set_guardians: "set_guardians",
    set_local_deposit: "set_local_deposit",
    set_lockup_code_deployers: "set_lockup_code_deployers",
    set_lockup_contract: "set_lockup_contract",
    set_staking_pool_whitelist_account_id: "set_staking_pool_whitelist_account_id",
    set_unlock_duration_sec: "set_unlock_duration_sec",
    storage_balance_bounds: "storage_balance_bounds",
    storage_balance_of: "storage_balance_of",
    storage_deposit: "storage_deposit",
    storage_withdraw: "storage_withdraw",
    undelegate: "undelegate",
    unpause: "unpause",
};
// =================================================
/// String constants for hos venear contract method names.
pub struct HOS_VENEAR_METHODS_CONST_TYPE {
    pub accept_ownership: &'static str,
    pub contract_source_metadata: &'static str,
    pub delegate_all: &'static str,
    pub deploy_lockup: &'static str,
    pub ft_balance_of: &'static str,
    pub ft_metadata: &'static str,
    pub ft_total_supply: &'static str,
    pub ft_transfer: &'static str,
    pub ft_transfer_call: &'static str,
    pub get_account_by_index: &'static str,
    pub get_account_info: &'static str,
    pub get_accounts: &'static str,
    pub get_accounts_raw: &'static str,
    pub get_config: &'static str,
    pub get_lockup_account_id: &'static str,
    pub get_lockup_deployment_cost: &'static str,
    pub get_num_accounts: &'static str,
    pub get_proof: &'static str,
    pub get_snapshot: &'static str,
    pub get_version: &'static str,
    pub is_paused: &'static str,
    pub migrate_state: &'static str,
    pub new: &'static str,
    pub on_lockup_deployed: &'static str,
    pub on_lockup_update: &'static str,
    pub pause: &'static str,
    pub propose_new_owner_account_id: &'static str,
    pub set_guardians: &'static str,
    pub set_local_deposit: &'static str,
    pub set_lockup_code_deployers: &'static str,
    pub set_lockup_contract: &'static str,
    pub set_staking_pool_whitelist_account_id: &'static str,
    pub set_unlock_duration_sec: &'static str,
    pub storage_balance_bounds: &'static str,
    pub storage_balance_of: &'static str,
    pub storage_deposit: &'static str,
    pub storage_withdraw: &'static str,
    pub undelegate: &'static str,
    pub unpause: &'static str,
}
// =================================================
// =================================================
// copyright 2026 by sleet.near