// =================================================
/// Method name constants for the meme-cooking meme launchpad / farming contract.
pub const MEME_COOKING_METHODS_CONST: MEME_COOKING_METHODS_CONST_TYPE = MEME_COOKING_METHODS_CONST_TYPE {
    pause: "pause",
    resume: "resume",
    create_meme: "create_meme",
    withdraw: "withdraw",
    on_withdraw: "on_withdraw",
    claim: "claim",
    on_claim: "on_claim",
    claim_vesting: "claim_vesting",
    on_claim_vesting: "on_claim_vesting",
    claim_income: "claim_income",
    on_claim_income: "on_claim_income",
    claim_shitstars: "claim_shitstars",
    on_claim_shitstars: "on_claim_shitstars",
    finalize: "finalize",
    on_finalize: "on_finalize",
    add_guardian: "add_guardian",
    remove_guardian: "remove_guardian",
    set_token_config: "set_token_config",
    set_fees: "set_fees",
    collect_fees: "collect_fees",
    migrate: "migrate",
    migrate_part: "migrate_part",
    migrate_self: "migrate_self",
    upgrade: "upgrade",
    upgrade_and_migrate: "upgrade_and_migrate",
    storage_deposit: "storage_deposit",
    storage_withdraw: "storage_withdraw",
    storage_unregister: "storage_unregister",
    storage_balance_bounds: "storage_balance_bounds",
    storage_balance_of: "storage_balance_of",
    ft_on_transfer: "ft_on_transfer",
    get_meme: "get_meme",
    get_finalized_meme: "get_finalized_meme",
    get_meme_stakes: "get_meme_stakes",
    get_finalizable_memes: "get_finalizable_memes",
    get_account: "get_account",
    get_unclaimed: "get_unclaimed",
    get_claimable: "get_claimable",
    get_claimable_withdraw_fees: "get_claimable_withdraw_fees",
    required_stake: "required_stake",
    whitelisted_token_ids: "whitelisted_token_ids",
    get_fees: "get_fees",
    get_guardians: "get_guardians",
    get_collected_fees: "get_collected_fees",
    create_meme_storage_cost: "create_meme_storage_cost",
    storage_costs: "storage_costs",
    is_running: "is_running",
    contract_source_metadata: "contract_source_metadata",
    new: "new",
};
// =================================================
/// String constants for meme-cooking contract method names.
pub struct MEME_COOKING_METHODS_CONST_TYPE {
    pub pause: &'static str,
    pub resume: &'static str,
    pub create_meme: &'static str,
    pub withdraw: &'static str,
    pub on_withdraw: &'static str,
    pub claim: &'static str,
    pub on_claim: &'static str,
    pub claim_vesting: &'static str,
    pub on_claim_vesting: &'static str,
    pub claim_income: &'static str,
    pub on_claim_income: &'static str,
    pub claim_shitstars: &'static str,
    pub on_claim_shitstars: &'static str,
    pub finalize: &'static str,
    pub on_finalize: &'static str,
    pub add_guardian: &'static str,
    pub remove_guardian: &'static str,
    pub set_token_config: &'static str,
    pub set_fees: &'static str,
    pub collect_fees: &'static str,
    pub migrate: &'static str,
    pub migrate_part: &'static str,
    pub migrate_self: &'static str,
    pub upgrade: &'static str,
    pub upgrade_and_migrate: &'static str,
    pub storage_deposit: &'static str,
    pub storage_withdraw: &'static str,
    pub storage_unregister: &'static str,
    pub storage_balance_bounds: &'static str,
    pub storage_balance_of: &'static str,
    pub ft_on_transfer: &'static str,
    pub get_meme: &'static str,
    pub get_finalized_meme: &'static str,
    pub get_meme_stakes: &'static str,
    pub get_finalizable_memes: &'static str,
    pub get_account: &'static str,
    pub get_unclaimed: &'static str,
    pub get_claimable: &'static str,
    pub get_claimable_withdraw_fees: &'static str,
    pub required_stake: &'static str,
    pub whitelisted_token_ids: &'static str,
    pub get_fees: &'static str,
    pub get_guardians: &'static str,
    pub get_collected_fees: &'static str,
    pub create_meme_storage_cost: &'static str,
    pub storage_costs: &'static str,
    pub is_running: &'static str,
    pub contract_source_metadata: &'static str,
    pub new: &'static str,
}
// =================================================
// =================================================
// copyright 2026 by sleet.near