// =================================================
/// Method name constants for the pumpopoly world.monopoly-style game contract.
pub const PUMPOPOLY_WORLD_METHODS_CONST: PUMPOPOLY_WORLD_METHODS_CONST_TYPE = PUMPOPOLY_WORLD_METHODS_CONST_TYPE {
    new: "new",
    award_land: "award_land",
    set_player_count: "set_player_count",
    set_player_invites: "set_player_invites",
    set_player_invited_by: "set_player_invited_by",
    set_player_balance: "set_player_balance",
    elite_build: "elite_build",
    on_elite_build: "on_elite_build",
    build: "build",
    move_player: "move_player",
    elite_move: "elite_move",
    on_elite_move: "on_elite_move",
    helicopter: "helicopter",
    taper: "taper",
    end_sale: "end_sale",
    sell_land: "sell_land",
    exchequer_claim_bond: "exchequer_claim_bond",
    on_exchequer_claim_bond: "on_exchequer_claim_bond",
    exchequer_buy_land: "exchequer_buy_land",
    buy_land: "buy_land",
    nft_on_transfer: "nft_on_transfer",
    mint_nft: "mint_nft",
    claim_nft: "claim_nft",
    sync_nft: "sync_nft",
    on_buy_tokens: "on_buy_tokens",
    on_nft_export: "on_nft_export",
    on_mint_request_settlement: "on_mint_request_settlement",
    ft_on_transfer: "ft_on_transfer",
    metadata: "metadata",
    view_market: "view_market",
    view_lands: "view_lands",
    view_players: "view_players",
    view_player: "view_player",
    view_player_count: "view_player_count",
};
// =================================================
/// String constants for pumpopoly world contract method names.
pub struct PUMPOPOLY_WORLD_METHODS_CONST_TYPE {
    pub new: &'static str,
    pub award_land: &'static str,
    pub set_player_count: &'static str,
    pub set_player_invites: &'static str,
    pub set_player_invited_by: &'static str,
    pub set_player_balance: &'static str,
    pub elite_build: &'static str,
    pub on_elite_build: &'static str,
    pub build: &'static str,
    pub move_player: &'static str,
    pub elite_move: &'static str,
    pub on_elite_move: &'static str,
    pub helicopter: &'static str,
    pub taper: &'static str,
    pub end_sale: &'static str,
    pub sell_land: &'static str,
    pub exchequer_claim_bond: &'static str,
    pub on_exchequer_claim_bond: &'static str,
    pub exchequer_buy_land: &'static str,
    pub buy_land: &'static str,
    pub nft_on_transfer: &'static str,
    pub mint_nft: &'static str,
    pub claim_nft: &'static str,
    pub sync_nft: &'static str,
    pub on_buy_tokens: &'static str,
    pub on_nft_export: &'static str,
    pub on_mint_request_settlement: &'static str,
    pub ft_on_transfer: &'static str,
    pub metadata: &'static str,
    pub view_market: &'static str,
    pub view_lands: &'static str,
    pub view_players: &'static str,
    pub view_player: &'static str,
    pub view_player_count: &'static str,
}
// =================================================
// =================================================
// copyright 2026 by sleet.near