// =================================================
/// Method name constants for the linear-protocol.near LiNEAR liquid-staking contract.
pub const LINEAR_PROTOCOL_METHODS_CONST: LINEAR_PROTOCOL_METHODS_CONST_TYPE = LINEAR_PROTOCOL_METHODS_CONST_TYPE {
    upgrade: "upgrade",
    epoch_stake: "epoch_stake",
    epoch_unstake: "epoch_unstake",
    epoch_update_rewards: "epoch_update_rewards",
    epoch_withdraw: "epoch_withdraw",
    validator_staked_callback: "validator_staked_callback",
    validator_unstaked_callback: "validator_unstaked_callback",
    validator_get_balance_callback: "validator_get_balance_callback",
    validator_get_account_callback: "validator_get_account_callback",
    validator_withdraw_callback: "validator_withdraw_callback",
    ft_transfer: "ft_transfer",
    ft_transfer_call: "ft_transfer_call",
    ft_total_supply: "ft_total_supply",
    ft_balance_of: "ft_balance_of",
    ft_resolve_transfer: "ft_resolve_transfer",
    ft_price: "ft_price",
    ft_metadata: "ft_metadata",
    storage_deposit: "storage_deposit",
    storage_withdraw: "storage_withdraw",
    storage_unregister: "storage_unregister",
    storage_balance_bounds: "storage_balance_bounds",
    storage_balance_of: "storage_balance_of",
    contract_source_metadata: "contract_source_metadata",
    set_owner: "set_owner",
    add_manager: "add_manager",
    remove_manager: "remove_manager",
    set_beneficiary: "set_beneficiary",
    remove_beneficiary: "remove_beneficiary",
    set_treasury: "set_treasury",
    set_whitelist_contract_id: "set_whitelist_contract_id",
    pause: "pause",
    resume: "resume",
    ping: "ping",
    deposit: "deposit",
    deposit_and_stake: "deposit_and_stake",
    withdraw_all: "withdraw_all",
    withdraw: "withdraw",
    stake_all: "stake_all",
    stake: "stake",
    unstake_all: "unstake_all",
    unstake: "unstake",
    migrate: "migrate",
    add_validator: "add_validator",
    add_validators: "add_validators",
    is_whitelisted_callback: "is_whitelisted_callback",
    remove_validator: "remove_validator",
    update_weight: "update_weight",
    update_weights: "update_weights",
    update_base_stake_amounts: "update_base_stake_amounts",
    sync_balance_from_validator: "sync_balance_from_validator",
    get_validator: "get_validator",
    get_validators: "get_validators",
    drain_unstake: "drain_unstake",
    drain_withdraw: "drain_withdraw",
    validator_drain_unstaked_callback: "validator_drain_unstaked_callback",
    validator_drain_withdraw_callback: "validator_drain_withdraw_callback",
    get_total_share_amount: "get_total_share_amount",
    get_beneficiaries: "get_beneficiaries",
    get_managers: "get_managers",
    get_summary: "get_summary",
    get_account_details: "get_account_details",
    get_account_unstaked_balance: "get_account_unstaked_balance",
    get_account_staked_balance: "get_account_staked_balance",
    get_account_total_balance: "get_account_total_balance",
    is_account_unstaked_balance_available: "is_account_unstaked_balance_available",
    get_total_staked_balance: "get_total_staked_balance",
    get_owner_id: "get_owner_id",
    get_reward_fee_fraction: "get_reward_fee_fraction",
    get_staking_key: "get_staking_key",
    is_paused: "is_paused",
    get_account: "get_account",
    get_number_of_accounts: "get_number_of_accounts",
    get_accounts: "get_accounts",
    can_account_withdraw: "can_account_withdraw",
    new: "new",
    version: "version",
};
// =================================================
/// String constants for linear-protocol.near contract method names.
pub struct LINEAR_PROTOCOL_METHODS_CONST_TYPE {
    pub upgrade: &'static str,
    pub epoch_stake: &'static str,
    pub epoch_unstake: &'static str,
    pub epoch_update_rewards: &'static str,
    pub epoch_withdraw: &'static str,
    pub validator_staked_callback: &'static str,
    pub validator_unstaked_callback: &'static str,
    pub validator_get_balance_callback: &'static str,
    pub validator_get_account_callback: &'static str,
    pub validator_withdraw_callback: &'static str,
    pub ft_transfer: &'static str,
    pub ft_transfer_call: &'static str,
    pub ft_total_supply: &'static str,
    pub ft_balance_of: &'static str,
    pub ft_resolve_transfer: &'static str,
    pub ft_price: &'static str,
    pub ft_metadata: &'static str,
    pub storage_deposit: &'static str,
    pub storage_withdraw: &'static str,
    pub storage_unregister: &'static str,
    pub storage_balance_bounds: &'static str,
    pub storage_balance_of: &'static str,
    pub contract_source_metadata: &'static str,
    pub set_owner: &'static str,
    pub add_manager: &'static str,
    pub remove_manager: &'static str,
    pub set_beneficiary: &'static str,
    pub remove_beneficiary: &'static str,
    pub set_treasury: &'static str,
    pub set_whitelist_contract_id: &'static str,
    pub pause: &'static str,
    pub resume: &'static str,
    pub ping: &'static str,
    pub deposit: &'static str,
    pub deposit_and_stake: &'static str,
    pub withdraw_all: &'static str,
    pub withdraw: &'static str,
    pub stake_all: &'static str,
    pub stake: &'static str,
    pub unstake_all: &'static str,
    pub unstake: &'static str,
    pub migrate: &'static str,
    pub add_validator: &'static str,
    pub add_validators: &'static str,
    pub is_whitelisted_callback: &'static str,
    pub remove_validator: &'static str,
    pub update_weight: &'static str,
    pub update_weights: &'static str,
    pub update_base_stake_amounts: &'static str,
    pub sync_balance_from_validator: &'static str,
    pub get_validator: &'static str,
    pub get_validators: &'static str,
    pub drain_unstake: &'static str,
    pub drain_withdraw: &'static str,
    pub validator_drain_unstaked_callback: &'static str,
    pub validator_drain_withdraw_callback: &'static str,
    pub get_total_share_amount: &'static str,
    pub get_beneficiaries: &'static str,
    pub get_managers: &'static str,
    pub get_summary: &'static str,
    pub get_account_details: &'static str,
    pub get_account_unstaked_balance: &'static str,
    pub get_account_staked_balance: &'static str,
    pub get_account_total_balance: &'static str,
    pub is_account_unstaked_balance_available: &'static str,
    pub get_total_staked_balance: &'static str,
    pub get_owner_id: &'static str,
    pub get_reward_fee_fraction: &'static str,
    pub get_staking_key: &'static str,
    pub is_paused: &'static str,
    pub get_account: &'static str,
    pub get_number_of_accounts: &'static str,
    pub get_accounts: &'static str,
    pub can_account_withdraw: &'static str,
    pub new: &'static str,
    pub version: &'static str,
}
// =================================================
// =================================================
// copyright 2026 by sleet.near