// =================================================
/// Method name constants for the house-of-stake lockup contract.
///
/// The lockup contract is deployed per-user (not a single global id), so no
/// contract-id const is provided — callers must supply the lockup account id
/// they are interacting with.
pub const HOS_LOCKUP_METHODS_CONST: HOS_LOCKUP_METHODS_CONST_TYPE = HOS_LOCKUP_METHODS_CONST_TYPE {
    begin_unlock_near: "begin_unlock_near",
    contract_source_metadata: "contract_source_metadata",
    delete_lockup: "delete_lockup",
    deposit_and_stake: "deposit_and_stake",
    deposit_to_staking_pool: "deposit_to_staking_pool",
    end_unlock_near: "end_unlock_near",
    get_balance: "get_balance",
    get_known_deposited_balance: "get_known_deposited_balance",
    get_liquid_owners_balance: "get_liquid_owners_balance",
    get_lockup_update_nonce: "get_lockup_update_nonce",
    get_owner_account_id: "get_owner_account_id",
    get_owners_balance: "get_owners_balance",
    get_staking_pool_account_id: "get_staking_pool_account_id",
    get_venear_liquid_balance: "get_venear_liquid_balance",
    get_venear_locked_balance: "get_venear_locked_balance",
    get_venear_pending_balance: "get_venear_pending_balance",
    get_venear_unlock_timestamp: "get_venear_unlock_timestamp",
    get_version: "get_version",
    lock_near: "lock_near",
    lock_pending_near: "lock_pending_near",
    new: "new",
    on_get_account_total_balance: "on_get_account_total_balance",
    on_get_account_unstaked_balance_to_withdraw_by_owner: "on_get_account_unstaked_balance_to_withdraw_by_owner",
    on_staking_pool_deposit: "on_staking_pool_deposit",
    on_staking_pool_deposit_and_stake: "on_staking_pool_deposit_and_stake",
    on_staking_pool_stake: "on_staking_pool_stake",
    on_staking_pool_unstake: "on_staking_pool_unstake",
    on_staking_pool_unstake_all: "on_staking_pool_unstake_all",
    on_staking_pool_withdraw: "on_staking_pool_withdraw",
    on_whitelist_is_whitelisted: "on_whitelist_is_whitelisted",
    refresh_staking_pool_balance: "refresh_staking_pool_balance",
    select_staking_pool: "select_staking_pool",
    stake: "stake",
    transfer: "transfer",
    unselect_staking_pool: "unselect_staking_pool",
    unstake: "unstake",
    unstake_all: "unstake_all",
    withdraw_all_from_staking_pool: "withdraw_all_from_staking_pool",
    withdraw_from_staking_pool: "withdraw_from_staking_pool",
};
// =================================================
/// String constants for hos lockup contract method names.
pub struct HOS_LOCKUP_METHODS_CONST_TYPE {
    pub begin_unlock_near: &'static str,
    pub contract_source_metadata: &'static str,
    pub delete_lockup: &'static str,
    pub deposit_and_stake: &'static str,
    pub deposit_to_staking_pool: &'static str,
    pub end_unlock_near: &'static str,
    pub get_balance: &'static str,
    pub get_known_deposited_balance: &'static str,
    pub get_liquid_owners_balance: &'static str,
    pub get_lockup_update_nonce: &'static str,
    pub get_owner_account_id: &'static str,
    pub get_owners_balance: &'static str,
    pub get_staking_pool_account_id: &'static str,
    pub get_venear_liquid_balance: &'static str,
    pub get_venear_locked_balance: &'static str,
    pub get_venear_pending_balance: &'static str,
    pub get_venear_unlock_timestamp: &'static str,
    pub get_version: &'static str,
    pub lock_near: &'static str,
    pub lock_pending_near: &'static str,
    pub new: &'static str,
    pub on_get_account_total_balance: &'static str,
    pub on_get_account_unstaked_balance_to_withdraw_by_owner: &'static str,
    pub on_staking_pool_deposit: &'static str,
    pub on_staking_pool_deposit_and_stake: &'static str,
    pub on_staking_pool_stake: &'static str,
    pub on_staking_pool_unstake: &'static str,
    pub on_staking_pool_unstake_all: &'static str,
    pub on_staking_pool_withdraw: &'static str,
    pub on_whitelist_is_whitelisted: &'static str,
    pub refresh_staking_pool_balance: &'static str,
    pub select_staking_pool: &'static str,
    pub stake: &'static str,
    pub transfer: &'static str,
    pub unselect_staking_pool: &'static str,
    pub unstake: &'static str,
    pub unstake_all: &'static str,
    pub withdraw_all_from_staking_pool: &'static str,
    pub withdraw_from_staking_pool: &'static str,
}
// =================================================
// =================================================
// copyright 2026 by sleet.near